import Head from 'next/head'
import Homepage from '@/components/home/Homepage'

export default function HowitWork() {
    return (
        <>
            <Head>
                <title>About us | GetEDPills</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Homepage />
        </>
    )
}
