import Cart from '@/components/Cart'
import Head from 'next/head'

export default function CartPage() {
    return (
        <>
            <Head>
                <title>Cart | FastEDPills</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Cart />
        </>
    )
}
