import Case from '@/components/case/Index'
import Head from 'next/head'

export default function CasePage() {
    return (
        <>
            <Head>
                <title>How it works | GetEDPills</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Case />
        </>
    )
}
