import Cialis from '@/components/products/cialis/Index'
import Head from 'next/head'

export default function ChialisPage() {
    return (
        <>
            <Head>
                <title>Cialis | FastEDPills</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Cialis />
        </>
    )
}
