import Head from 'next/head'

export default function HowitWork() {
    return (
        <>
            <Head>
                <title>Contact us | GetEDPills</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='h-96 flex justify-center items-center text-center'>

                <h1 className='theme-heading'>Content will be added soon</h1>
            </div>
        </>
    )
}
