import Membership from '@/components/Membership'
import Head from 'next/head'
import React from 'react'

const MembershipPage = () => {
    return (
        <>
            <Head>
                <title>Membership | GetEDPills</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Membership />
        </>
    )
}

export default MembershipPage