import Questionnaire from '@/components/questionnaire/Questionnaire'
import Head from 'next/head'

export default function HowitWork() {
    return (
        <>
            <Head>
                <title>Recommendation Questions | GetEDPills</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Questionnaire />
        </>
    )
}
