import Orders from '@/components/Orders'
import Head from 'next/head'
import React from 'react'

const ordersPage = () => {
    return (
        <>
            <Head>
                <title>Orders | GetEDPills</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Orders />
        </>
    )
}

export default ordersPage