import Sildenafil from '@/components/products/sildenafil/Index'
import Head from 'next/head'

const sildenafilPage = () => {
    return (
        <>
            <Head>
                <title>Sildenafil | FastEDPills</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Sildenafil />
        </>
    )
}

export default sildenafilPage