
import Tadalafil from '@/components/products/tadalafil/Index'
import Head from 'next/head'

const TadalafilPage = () => {
    return (
        <>
            <Head>
                <title>Tadalafil | GetEDPills</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Tadalafil />
        </>
    )
}

export default TadalafilPage